resolver: lts-13.21

packages:
- '.'

extra-deps:
- ConfigFile-1.1.4
- llvm-hs-pure-8.0.0
- llvm-hs-8.0.0
- text-replace-0.0.0.4
- sbv-8.2
- git: https://github.com/granule-project/granule
  commit: f6b3b5d4cf220e211d15e706b8a9c5c5883d6f8a
  subdirs:
  - frontend



# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []