resolver: lts-15.13

packages:
- '.'

extra-deps:
- ConfigFile-1.1.4
- llvm-hs-pure-9.0.0
- llvm-hs-9.0.1
- text-replace-0.0.0.4
- sbv-8.5
- syz-0.2.0.0@sha256:7307acb8f6ae7720e7e235c974281ecee912703c1394ebcac19caf83d70bb492,2345
- git: https://github.com/granule-project/granule
  commit: 26f37f0f97861ea14bd1b409c672a1519ce16a95
  subdirs:
  - frontend



# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
